### PR TITLE
Minor improvements and fix unreliable test case

### LINKED ISSUE #42: Test suite not reliable?
Looking at this build: https://travis-ci.org/twingly/twingly-amqp/builds/131445014 it seems like the test suite is luck dependant. I am thinking that the ping has not been carried out before the check of size: https://github.com/twingly/twingly-amqp/blob/04bd79b8c1c655b3fb4d69f849183751588a5e86/spec/integration/twingly/amqp/pinger_spec.rb#L37-L42

### PR DESCRIPTION
**Pull request by walro**
Fix #42.

I took the easy sleeping route here as that's what we did
in all other tests.

I think it could be better to check the queue length
something like "wait until we can see message on queue" but I couldn't find
a, simple, reliable solution, during my tests I would, sometimes, end up with for-ever sleeping threads.
I believe there are timing issues at hand that are hard to "quick fix".

### CODE REVIEW

**Comment by walro** [comment]
Somewhat related, I thought it was interesting to see how Bunny does their integration tests and the `sleep` route is not unheard of, see for example: https://github.com/ruby-amqp/bunny/blob/cbeb16036e3987968fb0731f008bbea7b6b3e762/spec/higher_level_api/integration/basic_publish_spec.rb#L47 (it's very easy to find more sleeps).

**Comment by walro** [comment]
Oh, great. This test run exposed another timing issue with the library's tests, see: https://travis-ci.org/twingly/twingly-amqp/builds/132226830. I'll create an issue concerning that.

**Comment by walro** [comment]
> Oh, great. This test run exposed another timing issue with the library's tests, see: https://travis-ci.org/twingly/twingly-amqp/builds/132226830. I'll create an issue concerning that.

Heh, TIL that re-running a test does not create a new build identifier so I have overwritten the build with the problem now 😄

File: spec/integration/twingly/amqp/pinger_spec.rb [hunk 1]
```diff
@@ -36,6 +36,7 @@
 
       before do
         subject.ping(urls, ping_options)
+        sleep 1
```
Comment (jage) [inline spec/integration/twingly/amqp/pinger_spec.rb]: Maybe a comment why we sleep here?

**Comment by jage** [comment]
LGTM (just https://github.com/twingly/twingly-amqp/pull/43#discussion_r64195733)!

File: spec/integration/twingly/amqp/pinger_spec.rb (hunk 1 above)
Comment (walro) [inline spec/integration/twingly/amqp/pinger_spec.rb]: There are 6 more `sleep 1` in the tests, 7 comments is a bit over the top. Perhaps it's possible to refactor a bit, so at least the ping spec and the subscription spec wraps the sleeping in a helper method.

Comment (jage) [inline spec/integration/twingly/amqp/pinger_spec.rb]: Sure, I thought it was extra-weird here though since we sleep in the `it`-block as well https://github.com/twingly/twingly-amqp/pull/43/files#diff-246ba8358de5fa9b5fe77d77fe3c4581R45

Comment (walro) [inline spec/integration/twingly/amqp/pinger_spec.rb]: Ah yeah, true!
