### PR TITLE
Configure pattern and ability to set logger

### LINKED ISSUE #46: Log exceptions happening in on_exception
I think it would be useful to log all exceptions happening in [`Subscription#on_exception`](https://github.com/twingly/twingly-amqp/blob/v4.1.0/lib/twingly/amqp/subscription.rb#L55-L57), either by default, or that the user supply the logger (and we default to [a null logger](https://github.com/avdi/naught)).

Example in one of our projects: https://github.com/twingly/wally/pull/47

### PR DESCRIPTION
**Pull request by walro**
Close #46.

### CODE REVIEW

File: spec/integration/twingly/amqp/subscription_spec.rb [hunk 1]
```diff
@@ -95,6 +95,28 @@
...
+          Twingly::AMQP.configure do |config|
+            config.logger = logger
+          end
+        end
+
+        it "logs the error" do
+          expect(logger).to receive(:error)
+
+          exchange.publish("this is not json", routing_key: routing_key)
+          sleep 1
```
Comment (walro) [inline spec/integration/twingly/amqp/subscription_spec.rb]: will fix if #50 makes it to master
