### PR TITLE
Do not convert Array to Hash when publishing

### LINKED ISSUE #71: Publishing an Array raises error or yields unexpected result
The problem is that Array responds to `#to_h`: https://github.com/twingly/twingly-amqp/blob/f0484795f528822f158df3314eb218df25de9379/lib/twingly/amqp/default_exchange_publisher.rb#L15-L21

For example, if you want to publish the message `[["1", "2"],["3", "4"]]` as JSON you would end up with `{"1":"2","3":"4"}` which may not be what you would expect.

Trying to publish a message with the following structure `[{type: "insert"},{type: "update"}]` just raises an error: `twingly/amqp/default_exchange_publisher.rb:18:in 'to_h': wrong element type Hash at 0 (expected array) (TypeError)`.

Same problem in both publisher classes (DefaultExchangePublisher, TopicExchangePublisher).

### PR DESCRIPTION
**Pull request by roback**
This changes the behaviour a bit, so a major version bump is needed for this (although to my knowledge we have ever used the Array->Hash conversion in any of our projects).

Had to use `.kind_of?(Array)` instead of `.respond_to?(:to_a)` since ruby Hashes responds to `to_a` and we don't want to convert all Hashes to Arrays.

close #71

### CODE REVIEW

File: spec/publisher_examples.rb [hunk 1]
```diff
@@ -1,26 +1,42 @@
...
-          actual_payload = JSON.parse(json_payload, symbolize_names: true)
-          expect(actual_payload).to eq(expected_payload)
+          expect(actual_payload).to eq(payload)
         end
       end
     end
 
-    context "when given a non-hash payload" do
-      let(:payload) { "not a hash" }
+    context "when given a non-hash/non-array payload" do
```
Comment (walro) [inline spec/publisher_examples.rb]: perhaps just go with `incompatible payload` so we don't have to change sentence this every time :D

Comment (roback) [reply spec/publisher_examples.rb]: hehe, sure :)

Comment (roback) [reply spec/publisher_examples.rb]: 8681064

File: spec/publisher_examples.rb [hunk 2]
```diff
@@ -1,26 +1,42 @@
...
+    let(:actual_payload) { JSON.parse(json_payload, symbolize_names: true) }
+
+    context "when given a valid payload" do
+      before do
+        subject.publish_with_confirm(payload)
+      end
+
+      [
+        { some: "data" },
+        OpenStruct.new(some: "data"),
```
Comment (walro) [inline spec/publisher_examples.rb]: `nil` could be an interesting case here as it responds to `.to_h`

Comment (walro) [reply spec/publisher_examples.rb]: Just dropping this here too: `Struct.new("Test", :test).new("Test")`. It looks horrendous, so we should likely not add it :-)

File: spec/publisher_examples.rb [hunk 3]
```diff
@@ -1,26 +1,42 @@
...
+
 shared_examples "publisher" do
   let(:payload) { { some: "data" } }
 
   describe "#publish" do
-    [{ some: "data" }, [[:some, "data"]]].each do |payload|
-      context "when given a hash-like payload '#{payload}'" do
-        before do
-          subject.publish_with_confirm(payload)
+    let(:json_payload)   { amqp_queue.pop.last }
```
Comment (walro) [inline spec/publisher_examples.rb]: while this was good for DRY, I feel that it removed readability.

The old version `_, _, json_payload = amqp_queue.pop` is a bit more revealing concerning how things works (aha, `pop` returns three items, where the last one is the payload).

File: spec/publisher_examples.rb (hunk 2 above)
Comment (roback) [reply spec/publisher_examples.rb]: I used a Struct first, but switched to OpenStruct for that reason :)

Good point about `nil`

File: spec/publisher_examples.rb (hunk 3 above)
Comment (roback) [reply spec/publisher_examples.rb]: I only wanted this to be on a single line, thats why I switched to pop. I could just switch back to:

```ruby
let(:json_payload) do
  _, _, json_payload = amqp_queue.pop

  json_payload
end
```

---

To keep it on a single line we could do the following, although I think that looks a bit weird :)

```ruby
let(:json_payload) { amqp_queue.pop.yield_self { |_, _, json_payload| json_payload } }
```

Comment (walro) [reply spec/publisher_examples.rb]: hehe, I'd prefer the first version :)

Comment (roback) [reply spec/publisher_examples.rb]: > hehe, I'd prefer the first version :)

Yes, I do too :)

File: spec/publisher_examples.rb (hunk 2 above)
Comment (roback) [reply spec/publisher_examples.rb]: 6e12f022e71dd2c012526947b924e034260717ea

File: spec/publisher_examples.rb (hunk 3 above)
Comment (roback) [reply spec/publisher_examples.rb]: 58561b55bfa791711b885830d9b504dd7ec9b79b
