### PR TITLE
Publisher: Extract all duplicated methods to a base class

### LINKED ISSUE #71: Publishing an Array raises error or yields unexpected result
The problem is that Array responds to `#to_h`: https://github.com/twingly/twingly-amqp/blob/f0484795f528822f158df3314eb218df25de9379/lib/twingly/amqp/default_exchange_publisher.rb#L15-L21

For example, if you want to publish the message `[["1", "2"],["3", "4"]]` as JSON you would end up with `{"1":"2","3":"4"}` which may not be what you would expect.

Trying to publish a message with the following structure `[{type: "insert"},{type: "update"}]` just raises an error: `twingly/amqp/default_exchange_publisher.rb:18:in 'to_h': wrong element type Hash at 0 (expected array) (TypeError)`.

Same problem in both publisher classes (DefaultExchangePublisher, TopicExchangePublisher).

### PR DESCRIPTION
**Pull request by roback**
Was trying to fix #71, and noticed we had to do the same thing in two places, so I extracted the methods to a base class instead.

I don't remember if there was the reason to why we have two similar classes though.

### CODE REVIEW

**Comment by walro** [comment]
> I don't remember if there was the reason to why we have two similar classes though.

Don't think so. Nice find :)

However, I think one could instantiate a `BasePublisher` now and it would actually do something? Not sure if that is desirable? Maybe a design based on modules could work out better

**Comment by roback** [comment]
> However, I think one could instantiate a `BasePublisher` now and it would actually do something? Not sure if that is desirable? Maybe a design based on modules could work out better

I just thought of the `BasePublished` as an implementation detail that no one else should use. I'm not quite sure what happens if someone uses it actually. Maby it's possible to use [`private_constant`](https://ruby-doc.org/core-2.5.0/Module.html#method-i-private_constant), but I don't think it'll work in this case.

Haven't even considered using modules, but it's worth a try.

**Comment by walro** [comment]
> I just thought of the `BasePublished` as an implementation detail that no one else should use.

Hehe yes, I just came to think about it. In other languages you can mark the class as `abstract` to avoid that.

**Comment by roback** [comment]
> Maby it's possible to use [`private_constant`](https://ruby-doc.org/core-2.5.0/Module.html#method-i-private_constant), but I don't think it'll work in this case.

Apparently it does work :)

```
twingly-amqp mattias$ bundle console
irb(main):001:0> Twingly::AMQP::BasePublisher
  NameError (private constant Twingly::AMQP::BasePublisher referenced)
```

Don't think we have to add it though.

**Comment by roback** [comment]
There's not much difference between using a module and a base class. Don't think one is better than the other, so I think we can go either way.

<details><summary>Diff</summary>

```diff
diff --git a/lib/twingly/amqp/base_publisher.rb b/lib/twingly/amqp/base_publisher.rb
index 018fb13..cfe1225 100644
--- a/lib/twingly/amqp/base_publisher.rb
+++ b/lib/twingly/amqp/base_publisher.rb
@@ -4,11 +4,7 @@ require "ostruct"
 
 module Twingly
   module AMQP
-    class BasePublisher
-      def initialize(connection: nil)
-        @connection = connection || Connection.instance
-      end
-
+    module BasePublisher
       def publish(message)
         raise ArgumentError unless message.respond_to?(:to_h)
 
@@ -31,7 +27,7 @@ module Twingly
         yield options
       end
 
-      protected
+      private
 
       def options
         @options ||=
diff --git a/lib/twingly/amqp/default_exchange_publisher.rb b/lib/twingly/amqp/default_exchange_publisher.rb
index 1ec96ba..ef3235c 100644
--- a/lib/twingly/amqp/default_exchange_publisher.rb
+++ b/lib/twingly/amqp/default_exchange_publisher.rb
@@ -2,13 +2,14 @@ require "twingly/amqp/base_publisher"
 
 module Twingly
   module AMQP
-    class DefaultExchangePublisher < BasePublisher
-      def initialize(queue_name:, connection: nil)
-        super(connection: connection)
+    class DefaultExchangePublisher
+      include BasePublisher
 
+      def initialize(queue_name:, connection: nil)
         options.routing_key = queue_name
 
-        @exchange = @connection.create_channel.default_exchange
+        connection ||= Connection.instance
+        @exchange = connection.create_channel.default_exchange
       end
     end
   end
diff --git a/lib/twingly/amqp/topic_exchange_publisher.rb b/lib/twingly/amqp/topic_exchange_publisher.rb
index ca4d819..055e5a4 100644
--- a/lib/twingly/amqp/topic_exchange_publisher.rb
+++ b/lib/twingly/amqp/topic_exchange_publisher.rb
@@ -2,13 +2,14 @@ require "twingly/amqp/base_publisher"
 
 module Twingly
   module AMQP
-    class TopicExchangePublisher < BasePublisher
-      def initialize(exchange_name:, routing_key: nil, connection: nil, opts: {})
-        super(connection: connection)
+    class TopicExchangePublisher
+      include BasePublisher
 
+      def initialize(exchange_name:, routing_key: nil, connection: nil, opts: {})
         options.routing_key = routing_key
 
-        @exchange = @connection.create_channel.topic(exchange_name, opts)
+        connection ||= Connection.instance
+        @exchange = connection.create_channel.topic(exchange_name, opts)
       end
     end
   end
```

</details>

**Comment by walro** [comment]
I kind of like it, if module is renamed `BasePublisher` -> `Publisher`

**Comment by roback** [comment]
Sure, lets go with a module then

File: lib/twingly/amqp/default_exchange_publisher.rb [hunk 1]
```diff
@@ -1,48 +1,16 @@
-require "twingly/amqp/connection"
```
Comment (walro) [inline lib/twingly/amqp/default_exchange_publisher.rb]: this should still be here me thinks (same with other publisher) and it may be removed from the module.

Comment (roback) [reply lib/twingly/amqp/default_exchange_publisher.rb]: I had to move the call from the base class initializer to each class and I forgot this line.

Comment (roback) [reply lib/twingly/amqp/default_exchange_publisher.rb]: f76c507
